### ISSUE TITLE
[Install Bug]: Go egg install error

### ISSUE THREAD

**Issue by TonimatasDEV** [pelican-eggs/generic#10]
### Panel Version

1.0.0-beta6

### Wings Version

1.0.0-beta3

### Service

Go

### Modified

No, I don't modified the egg.

### Expected Behavior

Install my go discord bot and run

### Actual Behavior

When the egg install the dependencies it stops saying "compile: writing output: write $WORK/b101/_pkg_.a: no space left on device"

### Steps To Reproduce

1. Import the egg.
2. Create a new server and set the go egg.
3. Add go project with some dependencies. ([Here](https://github.com/TonimatasDEV/BotStudio) is the repo I used)
4. Wait to install and see the error.

### Install logs

https://pteropaste.com/1s13

**Comment by redthirten** [comment]
Your error says "no space left on device". Have you made sure this isn't the problem?

**Comment by TonimatasDEV** [comment]
> Your error says "no space left on device". Have you made sure this isn't the problem?

Yes, I have 410GB left in my machine. I tried changing server space between unlimited and limited to 10GB but it keeps with the same problem.

**Comment by QuintenQVD0** [comment]
> > Your error says "no space left on device". Have you made sure this isn't the problem?
> 
> Yes, I have 410GB left in my machine. I tried changing server space between unlimited and limited to 10GB but it keeps with the same problem.

Youe tempfs is full, update it in the wings config then restart the wings.
