### ISSUE TITLE
[Bug]: python generic

### ISSUE THREAD

**Issue by snow-of-the-mountain** [pelican-eggs/generic#11]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

python generic

### Modified

No, I did not modify the egg

### Expected Behavior

Should be able to install python app  dependencies

### Actual Behavior

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/mastodon-py/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/mastodon-py/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/mastodon-py/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/mastodon-py/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/mastodon-py/
ERROR: Could not find a version that satisfies the requirement Mastodon.py==1.8.1 (from versions: none)
ERROR: No matching distribution found for Mastodon.py==1.8.1

### Steps To Reproduce

Run pip install -r requirements.txt on any python version

### Install logs

https://ptero.co/vulekuyufa.properties

**Comment by snow-of-the-mountain** [comment]
I've done some troubleshooting steps like others have recommended I've disabled IPv6. I'm able to access the python site on the server I have a working Internet connection and I can dig the site from the current DNS provider I'm using

**Comment by QuintenQVD0** [comment]
It is trying to use port 443 what can not be done as only port 1024 + can be allocated.

**Comment by QuintenQVD0** [comment]
Also no way that install log is for this egg or is a modified version what is not supported.

**Comment by snow-of-the-mountain** [comment]
> Also no way that install log is for this egg or is a modified version what is not supported.

I ran the command how it was given if I was supposed to modify the command I wasn't made aware of it

> It is trying to use port 443 what can not be done as only port 1024 + can be allocated.

No it's obviously trying to download dependencies for the app which it must communicate over 443 with the python site to be able to grab those dependencies python is useless if you can't even grab dependencies. For EG if a node JS app requires discord.js and can't pull it because for odd reason it can't ever communicate with the NPM sit then that's really not a useful install of node JS

**Comment by QuintenQVD0** [comment]
> > Also no way that install log is for this egg or is a modified version what is not supported.
> 
> I ran the command how it was given if I was supposed to modify the command I wasn't made aware of it
> 
> > It is trying to use port 443 what can not be done as only port 1024 + can be allocated.
> 
> No it's obviously trying to download dependencies for the app which it must communicate over 443 with the python site to be able to grab those dependencies python is useless if you can't even grab dependencies. For EG if a node JS app requires discord.js and can't pull it because for odd reason it can't ever communicate with the NPM sit then that's really not a useful install of node JS

Reading all this you seem to be having firewall issues as it is with multiple eggs.

**Comment by snow-of-the-mountain** [comment]
I gave an example i'm not saying there is an issue with node JS it's only happening with Python

**Comment by snow-of-the-mountain** [comment]
Nodejs is able to download dependencies but Python is still not able to

**Comment by gOOvER** [comment]
i cant confirm this. Python generic works like charm
The timeout sounds  for me like a wrong configured Proxy or firewall.

Which bot you want to install with the generic egg?

**Comment by snow-of-the-mountain** [comment]
> i cant confirm this. Python generic works like charm The timeout sounds for me like a wrong configured Proxy or firewall.

We don't use a proxy or a firewall like that I've made a new server and messed with the mtu to see if that was the issue and I'm still getting the same problem if I don't use Docker python works just fine 
![Screenshot 2024-12-14 032841](https://github.com/user-attachments/assets/5d6dc7e4-5b76-43f2-99cd-d594731030be)
![image](https://github.com/user-attachments/assets/319d0983-d9cb-4ff9-bf21-976ab2bc3a34)


> Which bot you want to install with the generic egg?

I'm trying to run a proprietary non-public python app

**Comment by QuintenQVD0** [comment]
This then seems like a dns issue as it can not reach the debian repo's

You should try changing the containers dns servers. see: https://pterodactyl.io/panel/1.0/troubleshooting.html#containers-don-t-have-internet-probably-a-dns-issue

**Comment by QuintenQVD0** [comment]
or if the hostos is RHEL/CentOS
https://pterodactyl.io/panel/1.0/troubleshooting.html#firewalld-issues

**Comment by snow-of-the-mountain** [comment]
> This then seems like a dns issue as it can not reach the debian repo's
> 
> You should try changing the containers dns servers. see: https://pterodactyl.io/panel/1.0/troubleshooting.html#containers-don-t-have-internet-probably-a-dns-issue

I would think that it would be a DNS issue if it wasn't for the server using the same DNS as the containers which is Cloudflare DNS though I can try changing them to see if that fixes the issue

**Comment by snow-of-the-mountain** [comment]
It's the same issue no matter what DNS I use. I'm thinking that it's a deeper network issue outside of the server but if it was then the issue should be showing even if I wasn't using docker

**Comment by snow-of-the-mountain** [comment]
It was a mix of external MTU issues and internal security thinking the connection wasn't authorized this has been fixed
